"""add reason to clarifications

Revision ID: d9bfcf785824
Revises: 0fa9a91da331
Create Date: 2026-08-13 16:12:45.360324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bfcf785824'
down_revision: Union[str, Sequence[str], None] = '0fa9a91da331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clarifications', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clarifications', 'reason')
    # ### end Alembic commands ###
