"""add architecture models

Revision ID: dba5e0f25cc2
Revises: c259a260b497
Create Date: 2026-08-12 20:44:24.625314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dba5e0f25cc2'
down_revision: Union[str, Sequence[str], None] = 'c259a260b497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architectures_id'), 'architectures', ['id'], unique=False)
    op.create_index(op.f('ix_architectures_project_id'), 'architectures', ['project_id'], unique=False)
    op.create_table('architecture_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tradeoffs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_decisions_architecture_id'), 'architecture_decisions', ['architecture_id'], unique=False)
    op.create_index(op.f('ix_architecture_decisions_id'), 'architecture_decisions', ['id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_architecture_id'), 'components', ['architecture_id'], unique=False)
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture_id', sa.Integer(), nullable=False),
    sa.Column('source_component_id', sa.Integer(), nullable=False),
    sa.Column('target_component_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_architecture_id'), 'connections', ['architecture_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_source_component_id'), 'connections', ['source_component_id'], unique=False)
    op.create_index(op.f('ix_connections_target_component_id'), 'connections', ['target_component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_target_component_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_source_component_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_architecture_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_index(op.f('ix_components_architecture_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_architecture_decisions_id'), table_name='architecture_decisions')
    op.drop_index(op.f('ix_architecture_decisions_architecture_id'), table_name='architecture_decisions')
    op.drop_table('architecture_decisions')
    op.drop_index(op.f('ix_architectures_project_id'), table_name='architectures')
    op.drop_index(op.f('ix_architectures_id'), table_name='architectures')
    op.drop_table('architectures')
    # ### end Alembic commands ###
